app:
  annotations:
    reloader.stakater.com/auto: "true"
  namespace: api
  image: bankbetch/example-go
  tag: develop-xxxxx-1
  imagePullSecrets: dockerhub-secret
  port: 8080
  export: 80
  healthCheckPath:
    liveness: "/health"
    readiness: "/readiness"
  resources:
    requests:
      memory: "64Mi"
      cpu: 0.1
    limits:
      memory: "128Mi"
      cpu: 0.2
  topologySpreadConstraints: false
  terminationGracePeriodSeconds: 20
  enabledArgoRollouts: false
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
    type: RollingUpdate

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 1m
    nginx.ingress.kubernetes.io/proxy-read-timeout: '60'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '60'
    nginx.ingress.kubernetes.io/use-regex: 'true'
  hosts:
    - host: dev.bankbetch.dev
      path: "/api(/|$)(.*)"

  serviceType: ClusterIP

autoscaling:
  enabled: true
  # default: false
  minReplicas: 1
  maxReplicas: 100
  cpu:
    type: Utilization
    targetAverageValue: 90
  memory:
    type: AverageValue
    targetAverageValue: 50Mi
  # prometheus:
  #   - type: prometheus
  #     metricType: Value
  #     metadata:
  #       serverAddress: http://prometheus.mornitoring
  #       threshold: '0.4'
  #       query: 'sum(max(rate(container_cpu_usage_seconds_total{container=~"demo-api-dev"}[30s]))) by (container)'

envFrom: secrets-example-api-dev
hcpVault: 
  dataKey: example/api/dev

volumes:
  volumeMounts:
    - name: tz-config
      mountPath: /etc/localtime
  hostPath:
    - name: tz-config
      path: /usr/share/zoneinfo/Asia/Bangkok