
---
{{- if and .Values.envFrom .Values.hcpVault }}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ .Values.envFrom }}
  namespace: {{ .Values.app.namespace }}
spec:
  refreshInterval: {{ .Values.hcpVault.refreshInterval | default "1m0s" }}
  secretStoreRef:
    name: vault-secret
    kind: ClusterSecretStore
  target:
    name: {{ .Values.envFrom }}
  dataFrom:
    - key: {{ .Values.hcpVault.dataKey }}
{{- end }}