{{- if .Values.internalIngress.enabled }}
{{- $fullName := .Release.Name -}}
{{- $svcPort := .Values.app.port -}}
{{- $ingName := printf "%s-internal" $fullName -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- if .Values.internalIngress.annotations }}
  annotations:
  {{- range $key, $value := .Values.internalIngress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  name: {{ $ingName }}
  namespace: {{ .Values.app.namespace }}
spec:
  rules:
  {{- range .Values.internalIngress.hosts }}
  - host: {{ .host }}
    http:
      paths:
      - path: {{ .path }}
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}
            port:
              number: {{ $svcPort }}
  {{- end }}
{{- end }}