---
{{- if .Values.storage.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.storage.pvName }}
spec:
  storageClassName: {{ .Values.storage.storageClassName | default "ebs-gp3" }}
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: {{ .Values.storage.size | default "1Gi" }} # Doesn't really matter, as EFS does not enforce it anyway
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.storage.accessMode | default "ReadWriteOnce" }}
  {{- if .Values.storage.efs }}
  csi:
{{ toYaml .Values.storage.efs | indent 4 }}
  {{- end }}
{{- end }}