---
{{- $customName := printf "%s-external" .Release.Name -}}

{{- if .Values.autoscaling.enabled }}
{{- if .Values.autoscaling.default }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  metrics:
  {{- if .Values.autoscaling.pods }}
  - type: Pods
    pods:
{{ toYaml .Values.autoscaling.pods | indent 6 }}
  {{- end }}
  {{- if .Values.autoscaling.memory }}
  - type: Resource
    resource:
      name: memory
      target:
        type: {{ .Values.autoscaling.memory.type }}
        {{- if eq .Values.autoscaling.memory.type "Utilization" }}
        averageUtilization: {{ .Values.autoscaling.memory.targetAverageValue }}
        {{- else }}
        averageValue: {{ .Values.autoscaling.memory.targetAverageValue }}
        {{- end }}

  {{- end }}
  {{- if .Values.autoscaling.cpu }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: {{ .Values.autoscaling.cpu.type }}
        {{- if eq .Values.autoscaling.cpu.type "Utilization" }}
        averageUtilization: {{ .Values.autoscaling.cpu.targetAverageValue }}
        {{- else }}
        averageValue: {{ .Values.autoscaling.cpu.targetAverageValue }}
        {{- end }}
  {{- end }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  scaleTargetRef:
    kind: Deployment
    name: {{ .Release.Name }}
    apiVersion: apps/v1

{{- else }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ $customName }}
  namespace: {{ .Values.app.namespace }}
spec:
  scaleTargetRef:
    name: {{ .Release.Name }}
  pollingInterval: {{ .Values.autoscaling.interval | default 30 }}
  minReplicaCount: {{ .Values.autoscaling.minReplicas }}
  maxReplicaCount: {{ .Values.autoscaling.maxReplicas }}
  triggers:
  {{- if .Values.autoscaling.prometheus }}
  {{ range .Values.autoscaling.prometheus }}
  - type: prometheus
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- if .Values.autoscaling.cpu }}
  - type: cpu
    metricType: {{ .Values.autoscaling.cpu.type }}
    metadata:
      value: {{ .Values.autoscaling.cpu.targetAverageValue | quote }}
  {{- end }}
  {{- if .Values.autoscaling.memory }}
  - type: memory
    metricType: {{ .Values.autoscaling.cpu.type }}
    metadata:
      value: {{ .Values.autoscaling.memory.targetAverageValue | quote }}
  {{- end }}
{{- end }}
{{- end }}