---
{{- if .Values.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.name }}
  namespace: {{ .Values.app.namespace }}
spec:
  accessModes:
    - {{ .Values.storage.accessMode | default "ReadWriteOnce" }}
  storageClassName: {{ .Values.storage.storageClassName | default "ebs-gp3" }}
  resources:
    requests:
      storage: {{ .Values.storage.size | default "1Gi" }}
{{- end }}