apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: pipeline
data:
  accounts.demo: apiKey,login
  accounts.demo.enabled: "true"
  admin.enabled: "true"
  application.instanceLabelKey: argocd.argoproj.io/instance
  exec.enabled: "false"
  server.rbac.log.enforce.enable: "false"
  timeout.hard.reconciliation: "0s"
  timeout.reconciliation: "30s"
